Error chain compat
Orangenosecom/philipshue pull request #20
Opened 2016-12-09 07:00 UTC by andete

Introduce error-chain for error handling for better usability by crate uses. (Error, Display trait, ...)
Update: Fix builds and reduce changes from original error API.

2016-12-16 13:01 UTC, gugi9000 commented
Will is still be able to connect to https://www.meethue.com/api/nupnp without SSL?

2016-12-16 13:29 UTC, andete commented
Hmm, sorry, this last change was not supposed to be part of the pull request. I'll fix.

2016-12-16 18:34 UTC, LFalch requested changes
Using error-chain also seems make the documentation more complicated and harder to understand. Although I think I'm happy with the general idea of the crate.

Also, is it possible for you to remove the extra commits that you did in the past in your fork that would just complicate the history?

2016-12-16 18:34 UTC, LFalch commented on src/errors.rs
> +pub type Result<T> = ::std::result::Result<T, HueError>;
This can be generated by the macro.

2016-12-16 18:34 UTC, LFalch commented on src/errors.rs
> +        HueError, HueErrorKind, ResultExt;
You should add the Result as the fourth field here, so the macro also can generate that.

2016-12-16 18:34 UTC, LFalch commented on Cargo.toml
> +ssdp = { version = "0.5", optional = true }
I'm not sure whether this is in the scope of this PR

2016-12-16 18:34 UTC, LFalch commented on src/errors.rs
> +        BridgeError(address:String, description:String, error:BridgeError) {
This can still be added as a struct variant, although it doesn't seem possible to make documentation comments on the fields of the struct variant.

2016-12-16 18:34 UTC, LFalch commented on src/bridge.rs
> +///         Err(HueError(HueErrorKind::BridgeError(_,_,BridgeError::LinkButtonNotPressed),_)) => {
This would be very similar to what it was before if the `BridgeError` variant was a struct variant as stated further down.

2016-12-16 18:34 UTC, LFalch commented on src/json.in.rs
> +use ::errors::{HueErrorKind,Result};
Nitpick, but could you add a space after the comma?

2016-12-16 18:34 UTC, LFalch commented on src/errors.rs
> +            display("Bridge error: {} {} {:?}", address, description, error)
Writing the error firstly and then the address followed by the description would make more sense to me - and perhaps some punctuation in between.

2016-12-16 18:47 UTC, andete commented on src/json.in.rs
> +use ::errors::{HueErrorKind,Result};
I tend to not worry about these things and run "cargo fmt" at some point ;)

2016-12-16 18:48 UTC, andete commented on Cargo.toml
> +ssdp = { version = "0.5", optional = true }
It is in fact. ssdp 0.5 has merged a pull-request by me that integrates error-chain as well.

2016-12-16 18:49 UTC, LFalch commented on Cargo.toml
> +ssdp = { version = "0.5", optional = true }
That's right as well! Never mind my comment then. :)

2016-12-16 18:50 UTC, andete commented
If you don't mind I'll make a new pull-request this weekend with a clean history and the requested changes.
I do agree that error-chain complicates documentation, but so far I consider the benefits outweighing the cons.

2016-12-16 18:51 UTC, LFalch commented
@andete That's fine! I look forward to it :)

2016-12-17 05:20 UTC, andete commented
Closing pull request in preparation for new one.

2016-12-17 05:20 UTC, closed without merging